name: release

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-20.04

    steps:
      # Checks out a copy of your repository on the ubuntu-20.04 machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies with npm
        run: npm install

      - name: Genereate environment file
        run: npm run build:env
        env:
          API_URL: ${{ secrets.API_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - name: Build
        run: npm run build:prod
        env:
          NODE_ENV: "production"

      - name: Setup firebase tools
        run: npm install -g firebase-tools

      - name: Deploy web
        run: firebase deploy --only hosting  --project ${{ secrets.PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
