name: release

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-20.04

    steps:
      # Checks out a copy of your repository on the ubuntu-20.04 machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies with npm
        run: npm install

      - name: Genereate environment file
        run: |
          API_URL=${{ secrets.API_KEY }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          PROJECT_ID=${{ secrets.PROJECT_ID }}
          cp src/environments/environment.example.ts src/environments/environment.prod.ts
          sed -i "s|http://api.url.com|$API_URL|g" src/environments/environment.prod.ts
          sed -i "s|database_url|$DATABASE_URL|g" src/environments/environment.prod.ts
          sed -i "s|project_id|$PROJECT_ID|g" src/environments/environment.prod.ts
          cat src/environments/environment.prod.ts

      - name: Build
        run: npm run:prod

      - name: Setup firebase tools
        run: |
          npm install -g firebase-tools

      - name: Deploy web
        run: |
          firebase deploy --only hosting  --project ${{ secrets.PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
